"""Add table Faction

Revision ID: 025793a48582
Revises: ddeb09dd9b76
Create Date: 2020-05-18 16:52:22.623043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025793a48582'
down_revision = 'ddeb09dd9b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faction')
    # ### end Alembic commands ###
