"""Rename List table wit Band table

Revision ID: cf6df213cf41
Revises: 025793a48582
Create Date: 2020-05-18 20:39:46.385081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6df213cf41'
down_revision = '025793a48582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('format', sa.Integer(), nullable=True),
    sa.Column('faction', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_band_timestamp'), 'band', ['timestamp'], unique=False)
    op.drop_index('ix_list_timestamp', table_name='list')
    op.drop_table('list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('format', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_list_timestamp', 'list', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_band_timestamp'), table_name='band')
    op.drop_table('band')
    # ### end Alembic commands ###
